#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";

const BLOGS_DIR = join(import.meta.dir, "..", "content", "blogs");
const OUT = join(import.meta.dir, "..", "src", "blogs-data.ts");

function parseFrontmatter(raw: string) {
  const match = raw.match(/^\+\+\+\n([\s\S]*?)\n\+\+\+\n([\s\S]*)$/);
  if (!match) return { meta: { title: "", date: "", tags: [] as string[], draft: false }, content: raw };
  const toml = match[1];
  const content = match[2].trim();
  const titleMatch = toml.match(/^title\s*=\s*(?:"([^"]+)"|'([^']+)')/m);
  const title = titleMatch ? (titleMatch[1] ?? titleMatch[2] ?? "") : "";
  const dateMatch = toml.match(/^date\s*=\s*(?:"([^"]+)"|'([^']+)')/m);
  const date = dateMatch ? (dateMatch[1] ?? dateMatch[2] ?? "") : "";
  const draft = toml.match(/^draft\s*=\s*(true|false)/m)?.[1] === "true";
  const tagsMatch = toml.match(/^tags\s*=\s*\[([^\]]*)\]/m);
  const tags = tagsMatch
    ? tagsMatch[1].split(",").map(t => t.trim().replace(/^["']|["']$/g, "")).filter(Boolean)
    : [];
  return { meta: { title, date, tags, draft }, content };
}

let files: string[] = [];
try {
  files = readdirSync(BLOGS_DIR).filter(f => f.endsWith(".md"));
} catch {
  files = [];
}

const posts = files
  .map(file => {
    const slug = file.replace(/\.md$/, "");
    const raw = readFileSync(join(BLOGS_DIR, file), "utf-8");
    const { meta, content } = parseFrontmatter(raw);
    return { slug, ...meta, content };
  })
  .filter(p => !p.draft)
  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

const out = `// AUTO-GENERATED by scripts/generate-blogs.ts — do not edit by hand.
export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  tags: string[];
  draft: boolean;
  content: string;
}

export const posts: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`Wrote ${posts.length} post(s) to ${OUT}`);
